/* templates/scripts/make_title.svelte generated by Svelte v3.47.0 */
import { create_ssr_component } from "svelte/internal";

const makeTitle = filename => {
	if (filename == 'index.json') {
		return 'Home';
	} else if (filename) {
		// Remove file extension.
		filename = filename.split('.').slice(0, -1).join('.');

		// Convert underscores and hyphens to spaces.
		filename = filename.replace(/_|-/g, ' ');

		// Capitalize first letter of each word.
		filename = filename.split(' ').map(s => s.charAt(0).toUpperCase() + s.substring(1)).join(' ');
	}

	return filename;
};

const Make_title = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export default Make_title;
export { makeTitle };