/* templates/scripts/stores.js generated by Svelte v3.47.0 */
import { create_ssr_component } from "svelte/internal";

import { writable } from 'svelte/store';
const count = writable(0);

const Stores = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export default Stores;
export { count };