/* templates/global/nav.svelte generated by Svelte v3.47.0 */
import {
	SvelteComponentDev,
	add_location,
	append_hydration_dev,
	append_styles,
	attr_dev,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach_dev,
	dispatch_dev,
	element,
	init,
	insert_hydration_dev,
	noop,
	safe_not_equal,
	space,
	src_url_equal,
	text,
	validate_slots
} from "svelte/internal";

const file = "templates/global/nav.svelte";

function add_css(target) {
	append_styles(target, "svelte-1nwrdwq", "nav.svelte-1nwrdwq.svelte-1nwrdwq,.container.svelte-1nwrdwq.svelte-1nwrdwq,#brand.svelte-1nwrdwq.svelte-1nwrdwq,#brand.svelte-1nwrdwq a.svelte-1nwrdwq{display:flex}nav.svelte-1nwrdwq.svelte-1nwrdwq{min-height:60px;box-shadow:0px 2px 3px var(--base)}#brand.svelte-1nwrdwq.svelte-1nwrdwq{flex:1}a.svelte-1nwrdwq.svelte-1nwrdwq{align-self:center;align-items:center;color:var(--base-dark);text-decoration:none}img.svelte-1nwrdwq.svelte-1nwrdwq{margin-right:10px}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64, */");
}

function create_fragment(ctx) {
	let nav;
	let div;
	let span;
	let a0;
	let img;
	let img_src_value;
	let t0;
	let t1;
	let a1;
	let t2;
	let t3;
	let a2;
	let t4;
	let t5;
	let a3;
	let t6;

	const block = {
		c: function create() {
			nav = element("nav");
			div = element("div");
			span = element("span");
			a0 = element("a");
			img = element("img");
			t0 = text("Home");
			t1 = space();
			a1 = element("a");
			t2 = text("About");
			t3 = text(" \n    ");
			a2 = element("a");
			t4 = text("Contact");
			t5 = text(" \n    ");
			a3 = element("a");
			t6 = text("Admin");
			this.h();
		},
		l: function claim(nodes) {
			nav = claim_element(nodes, "NAV", { class: true });
			var nav_nodes = children(nav);
			div = claim_element(nav_nodes, "DIV", { class: true });
			var div_nodes = children(div);
			span = claim_element(div_nodes, "SPAN", { id: true, class: true });
			var span_nodes = children(span);
			a0 = claim_element(span_nodes, "A", { href: true, class: true });
			var a0_nodes = children(a0);
			img = claim_element(a0_nodes, "IMG", { alt: true, src: true, class: true });
			t0 = claim_text(a0_nodes, "Home");
			a0_nodes.forEach(detach_dev);
			span_nodes.forEach(detach_dev);
			t1 = claim_space(div_nodes);
			a1 = claim_element(div_nodes, "A", { href: true, class: true });
			var a1_nodes = children(a1);
			t2 = claim_text(a1_nodes, "About");
			a1_nodes.forEach(detach_dev);
			t3 = claim_text(div_nodes, " \n    ");
			a2 = claim_element(div_nodes, "A", { href: true, class: true });
			var a2_nodes = children(a2);
			t4 = claim_text(a2_nodes, "Contact");
			a2_nodes.forEach(detach_dev);
			t5 = claim_text(div_nodes, " \n    ");
			a3 = claim_element(div_nodes, "A", { href: true, class: true });
			var a3_nodes = children(a3);
			t6 = claim_text(a3_nodes, "Admin");
			a3_nodes.forEach(detach_dev);
			div_nodes.forEach(detach_dev);
			nav_nodes.forEach(detach_dev);
			this.h();
		},
		h: function hydrate() {
			attr_dev(img, "alt", "planarian");
			if (!src_url_equal(img.src, img_src_value = "logo.svg")) attr_dev(img, "src", img_src_value);
			attr_dev(img, "class", "svelte-1nwrdwq");
			add_location(img, file, 2, 33, 65);
			attr_dev(a0, "href", ".");
			attr_dev(a0, "class", "svelte-1nwrdwq");
			add_location(a0, file, 2, 21, 53);
			attr_dev(span, "id", "brand");
			attr_dev(span, "class", "svelte-1nwrdwq");
			add_location(span, file, 2, 4, 36);
			attr_dev(a1, "href", "about");
			attr_dev(a1, "class", "svelte-1nwrdwq");
			add_location(a1, file, 3, 4, 123);
			attr_dev(a2, "href", "contact");
			attr_dev(a2, "class", "svelte-1nwrdwq");
			add_location(a2, file, 4, 4, 159);
			attr_dev(a3, "href", "admin");
			attr_dev(a3, "class", "svelte-1nwrdwq");
			add_location(a3, file, 5, 4, 199);
			attr_dev(div, "class", "container svelte-1nwrdwq");
			add_location(div, file, 1, 2, 8);
			attr_dev(nav, "class", "svelte-1nwrdwq");
			add_location(nav, file, 0, 0, 0);
		},
		m: function mount(target, anchor) {
			insert_hydration_dev(target, nav, anchor);
			append_hydration_dev(nav, div);
			append_hydration_dev(div, span);
			append_hydration_dev(span, a0);
			append_hydration_dev(a0, img);
			append_hydration_dev(a0, t0);
			append_hydration_dev(div, t1);
			append_hydration_dev(div, a1);
			append_hydration_dev(a1, t2);
			append_hydration_dev(div, t3);
			append_hydration_dev(div, a2);
			append_hydration_dev(a2, t4);
			append_hydration_dev(div, t5);
			append_hydration_dev(div, a3);
			append_hydration_dev(a3, t6);
		},
		p: noop,
		i: noop,
		o: noop,
		d: function destroy(detaching) {
			if (detaching) detach_dev(nav);
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	let { $$slots: slots = {}, $$scope } = $$props;
	validate_slots('Nav', slots, []);
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== '$$' && key !== 'slot') console.warn(`<Nav> was created with unknown prop '${key}'`);
	});

	return [];
}

class Nav extends SvelteComponentDev {
	constructor(options) {
		super(options);
		init(this, options, instance, create_fragment, safe_not_equal, {}, add_css);

		dispatch_dev("SvelteRegisterComponent", {
			component: this,
			tagName: "Nav",
			options,
			id: create_fragment.name
		});
	}
}

export default Nav;