/* templates/content/_index.js generated by Svelte v3.47.0 */
import { create_ssr_component, each } from "svelte/internal";

const Index = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { title } = $$props;
	let intro = ["first thing", "second thing"];
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);

	return `<h1>Homepage title</h1>

<section id="${"intro"}">${each(intro, paragraph => {
		return `<p><!-- HTML_TAG_START -->${paragraph}<!-- HTML_TAG_END --></p>`;
	})}</section>`;
});

export default Index;