/* templates/content/blog.svelte generated by Svelte v3.47.0 */
import {
	create_ssr_component,
	each,
	escape,
	missing_component,
	validate_component
} from "svelte/internal";

import Uses from "../components/source.svelte";

// Svelte store example:
import { count } from '../scripts/stores.svelte';

import Incrementer from '../components/incrementer.svelte';
import Decrementer from '../components/decrementer.svelte';

const Blog = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { title, body, author, date, store, source, content } = $$props;
	let count_value;

	const unsubscribe = count.subscribe(value => {
		count_value = value;
	});

	let { components, allLayouts } = $$props;
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	if ($$props.body === void 0 && $$bindings.body && body !== void 0) $$bindings.body(body);
	if ($$props.author === void 0 && $$bindings.author && author !== void 0) $$bindings.author(author);
	if ($$props.date === void 0 && $$bindings.date && date !== void 0) $$bindings.date(date);
	if ($$props.store === void 0 && $$bindings.store && store !== void 0) $$bindings.store(store);
	if ($$props.source === void 0 && $$bindings.source && source !== void 0) $$bindings.source(source);
	if ($$props.content === void 0 && $$bindings.content && content !== void 0) $$bindings.content(content);
	if ($$props.components === void 0 && $$bindings.components && components !== void 0) $$bindings.components(components);
	if ($$props.allLayouts === void 0 && $$bindings.allLayouts && allLayouts !== void 0) $$bindings.allLayouts(allLayouts);

	return `<h1>${escape(title)}</h1>

<p><em>${author ? `Written by ${escape(author)}` : ``}${date ? ` on ${escape(date)}` : ``}</em></p>

<p><!-- HTML_TAG_START -->${body}<!-- HTML_TAG_END --></p>

${store
	? `<h3>The count is ${escape(count_value)}</h3>
  ${validate_component(Incrementer, "Incrementer").$$render($$result, {}, {}, {})}
  ${validate_component(Decrementer, "Decrementer").$$render($$result, {}, {}, {})}`
	: ``}

${components
	? `${each(components, ({ name }) => {
			return `${validate_component(allLayouts["layouts_components_" + name + "_svelte"] || missing_component, "svelte:component").$$render($$result, {}, {}, {})}`;
		})}`
	: ``}

${source
	? `${validate_component(Uses, "Uses").$$render($$result, { content, source }, {}, {})}`
	: ``}

<p><a href="${"."}">Back home</a></p>`;
});

export default Blog;