/* templates/content/blog.js generated by Svelte v3.47.0 */
import { create_ssr_component, escape } from "svelte/internal";

const Blog = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { title = "Blog title" } = $$props;
	let author = "jim";
	let date = "today";
	let body = "<ul><li>one</li><li>two</li></ul>";
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);

	return `<h1>${escape(title)}</h1>

<p><em>${author ? `Written by ${escape(author)}` : ``}${date ? ` on ${escape(date)}` : ``}</em></p>

<p><!-- HTML_TAG_START -->${body}<!-- HTML_TAG_END --></p>

<p><a href="${"."}">Back home</a></p>`;
});

export default Blog;