/* templates/components/decrementer.svelte generated by Svelte v3.47.0 */
import { create_ssr_component } from "svelte/internal";

import { count } from '../scripts/stores.svelte';

const Decrementer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	function decrement() {
		count.update(n => n - 1);
	}

	return `<button>-
</button>`;
});

export default Decrementer;