/* templates/components/incrementer.js generated by Svelte v3.47.0 */
import { create_ssr_component } from "svelte/internal";

import { count } from '../scripts/stores.js';

const Incrementer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	function increment() {
		count.update(n => n + 1);
	}

	return `<button>+
</button>`;
});

export default Incrementer;