/* templates/components/pager.js generated by Svelte v3.47.0 */
import {
	add_attribute,
	create_ssr_component,
	each,
	escape
} from "svelte/internal";

const css = {
	code: "ul.js-1tphcia{display:flex;max-width:600px;margin:20px auto}li.js-1tphcia{flex-grow:1;list-style:none}a.js-1tphcia{text-align:center;padding:5px 20px;border-radius:5px;background:#f0efef}span.js-1tphcia{text-align:center;padding:5px 20px;color:gray}",
	map: "{\"version\":3,\"file\":\"pager.js\",\"sources\":[\"pager.js\"],\"sourcesContent\":[\"<script>\\n  export let currentPage, totalPages;\\n</script>\\n\\n<ul>\\n  {#if currentPage > 1}\\n    <li><a href=\\\".\\\">first</a></li>\\n    <li><a href=\\\"{currentPage - 1}\\\">prev</a></li>\\n  {:else}\\n    <li><span>first</span></li>\\n    <li><span>prev</span></li>\\n  {/if}\\n  {#each [3,2,1] as i}\\n    {#if currentPage - i > 0}\\n      <li><a href=\\\"{currentPage - i}\\\">{currentPage - i}</a></li>\\n    {/if}\\n  {/each}\\n  <li><span>{currentPage}</span></li>\\n  {#each Array(3) as _, i}\\n    {#if currentPage + (i+1) <= totalPages}\\n      <li><a href=\\\"{currentPage + (i+1)}\\\">{currentPage + (i+1)}</a></li>\\n    {/if}\\n  {/each}\\n  {#if currentPage < totalPages}\\n    <li><a href=\\\"{currentPage + 1}\\\">next</a></li>\\n    <li><a href=\\\"{totalPages}\\\">last</a></li>\\n  {:else}\\n    <li><span>next</span></li>\\n    <li><span>last</span></li>\\n  {/if}\\n</ul>\\n\\n<style>\\n  ul {\\n    display: flex;\\n    max-width: 600px;\\n    margin: 20px auto;\\n  }\\n  li {\\n    flex-grow: 1;\\n    list-style: none;\\n  }\\n  a {\\n    text-align: center;\\n    padding: 5px 20px;\\n    border-radius: 5px;\\n    background: #f0efef;\\n  }\\n  span {\\n    text-align: center;\\n    padding: 5px 20px;\\n    color: gray;\\n  }\\n</style>\"],\"names\":[],\"mappings\":\"AAiCE,EAAE,eAAC,CAAC,AACF,OAAO,CAAE,IAAI,CACb,SAAS,CAAE,KAAK,CAChB,MAAM,CAAE,IAAI,CAAC,IAAI,AACnB,CAAC,AACD,EAAE,eAAC,CAAC,AACF,SAAS,CAAE,CAAC,CACZ,UAAU,CAAE,IAAI,AAClB,CAAC,AACD,CAAC,eAAC,CAAC,AACD,UAAU,CAAE,MAAM,CAClB,OAAO,CAAE,GAAG,CAAC,IAAI,CACjB,aAAa,CAAE,GAAG,CAClB,UAAU,CAAE,OAAO,AACrB,CAAC,AACD,IAAI,eAAC,CAAC,AACJ,UAAU,CAAE,MAAM,CAClB,OAAO,CAAE,GAAG,CAAC,IAAI,CACjB,KAAK,CAAE,IAAI,AACb,CAAC\"}"
};

const Pager = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { currentPage, totalPages } = $$props;
	if ($$props.currentPage === void 0 && $$bindings.currentPage && currentPage !== void 0) $$bindings.currentPage(currentPage);
	if ($$props.totalPages === void 0 && $$bindings.totalPages && totalPages !== void 0) $$bindings.totalPages(totalPages);
	$$result.css.add(css);

	return `<ul class="${"svelte-1tphcia"}">${currentPage > 1
	? `<li class="${"svelte-1tphcia"}"><a href="${"."}" class="${"svelte-1tphcia"}">first</a></li>
    <li class="${"svelte-1tphcia"}"><a${add_attribute("href", currentPage - 1, 0)} class="${"svelte-1tphcia"}">prev</a></li>`
	: `<li class="${"svelte-1tphcia"}"><span class="${"svelte-1tphcia"}">first</span></li>
    <li class="${"svelte-1tphcia"}"><span class="${"svelte-1tphcia"}">prev</span></li>`}
  ${each([3, 2, 1], i => {
		return `${currentPage - i > 0
		? `<li class="${"svelte-1tphcia"}"><a${add_attribute("href", currentPage - i, 0)} class="${"svelte-1tphcia"}">${escape(currentPage - i)}</a></li>`
		: ``}`;
	})}
  <li class="${"svelte-1tphcia"}"><span class="${"svelte-1tphcia"}">${escape(currentPage)}</span></li>
  ${each(Array(3), (_, i) => {
		return `${currentPage + (i + 1) <= totalPages
		? `<li class="${"svelte-1tphcia"}"><a${add_attribute("href", currentPage + (i + 1), 0)} class="${"svelte-1tphcia"}">${escape(currentPage + (i + 1))}</a></li>`
		: ``}`;
	})}
  ${currentPage < totalPages
	? `<li class="${"svelte-1tphcia"}"><a${add_attribute("href", currentPage + 1, 0)} class="${"svelte-1tphcia"}">next</a></li>
    <li class="${"svelte-1tphcia"}"><a${add_attribute("href", totalPages, 0)} class="${"svelte-1tphcia"}">last</a></li>`
	: `<li class="${"svelte-1tphcia"}"><span class="${"svelte-1tphcia"}">next</span></li>
    <li class="${"svelte-1tphcia"}"><span class="${"svelte-1tphcia"}">last</span></li>`}
</ul>`;
});

export default Pager;