/* templates/global/nav.js generated by Svelte v3.47.0 */
import { create_ssr_component } from "svelte/internal";

const css = {
	code: "nav.js-1nwrdwq.js-1nwrdwq,.container.js-1nwrdwq.js-1nwrdwq,#brand.js-1nwrdwq.js-1nwrdwq,#brand.js-1nwrdwq a.js-1nwrdwq{display:flex}nav.js-1nwrdwq.js-1nwrdwq{min-height:60px;box-shadow:0px 2px 3px var(--base)}#brand.js-1nwrdwq.js-1nwrdwq{flex:1}a.js-1nwrdwq.js-1nwrdwq{align-self:center;align-items:center;color:var(--base-dark);text-decoration:none}img.js-1nwrdwq.js-1nwrdwq{margin-right:10px}",
	map: "{\"version\":3,\"file\":\"nav.js\",\"sources\":[\"nav.js\"],\"sourcesContent\":[\"<nav>\\n  <div class=\\\"container\\\">\\n    <span id=\\\"brand\\\"><a href=\\\".\\\"><img alt=\\\"planarian\\\" src=\\\"logo.svg\\\" />Home</a></span>\\n    <a href=\\\"about\\\">About</a>&nbsp;\\n    <a href=\\\"contact\\\">Contact</a>&nbsp;\\n    <a href=\\\"admin\\\">Admin</a>\\n  </div>\\n</nav>\\n\\n<style>\\n  nav, .container, #brand, #brand a {\\n    display: flex;\\n  }\\n  nav {\\n    min-height: 60px;\\n    box-shadow: 0px 2px 3px var(--base);\\n  }\\n  #brand {\\n    flex: 1;\\n  }\\n  a {\\n    align-self: center;\\n    align-items: center;\\n    color: var(--base-dark);\\n    text-decoration: none;\\n  }\\n  img {\\n    margin-right: 10px;\\n  }\\n</style>\\n\"],\"names\":[],\"mappings\":\"AAUE,iCAAG,CAAE,wCAAU,CAAE,oCAAM,CAAE,qBAAM,CAAC,CAAC,eAAC,CAAC,AACjC,OAAO,CAAE,IAAI,AACf,CAAC,AACD,GAAG,8BAAC,CAAC,AACH,UAAU,CAAE,IAAI,CAChB,UAAU,CAAE,GAAG,CAAC,GAAG,CAAC,GAAG,CAAC,IAAI,MAAM,CAAC,AACrC,CAAC,AACD,MAAM,8BAAC,CAAC,AACN,IAAI,CAAE,CAAC,AACT,CAAC,AACD,CAAC,8BAAC,CAAC,AACD,UAAU,CAAE,MAAM,CAClB,WAAW,CAAE,MAAM,CACnB,KAAK,CAAE,IAAI,WAAW,CAAC,CACvB,eAAe,CAAE,IAAI,AACvB,CAAC,AACD,GAAG,8BAAC,CAAC,AACH,YAAY,CAAE,IAAI,AACpB,CAAC\"}"
};

const Nav = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);

	return `<nav class="${"svelte-1nwrdwq"}"><div class="${"container svelte-1nwrdwq"}"><span id="${"brand"}" class="${"svelte-1nwrdwq"}"><a href="${"."}" class="${"svelte-1nwrdwq"}"><img alt="${"planarian"}" src="${"logo.svg"}" class="${"svelte-1nwrdwq"}">Home</a></span>
    <a href="${"about"}" class="${"svelte-1nwrdwq"}">About</a> 
    <a href="${"contact"}" class="${"svelte-1nwrdwq"}">Contact</a> 
    <a href="${"admin"}" class="${"svelte-1nwrdwq"}">Admin</a></div>
</nav>`;
});

export default Nav;